services:
  websocket:
    image: lakhoune/yjs-websocket
    ports:
      - "1234:1234"
    environment:
      HOST: 0.0.0.0
      PORT: 1234
  db:
    image: postgres:17
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: inicio
      POSTGRES_PASSWORD: inicio
      POSTGRES_DB: inicio-db
    volumes:
      - pgdata-inicio:/var/lib/postgresql/data

volumes:
  pgdata-inicio:
