services:
  payload:
    image: node
    ports:
      - '3000:3000'
    volumes:
      - .:/home/node/app
    working_dir: /home/node/app/
    command: sh -c "corepack enable && corepack prepare pnpm@latest --activate && pnpm install && pnpm dev"
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    container_name: inicio_db
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_USER: inicio
      POSTGRES_PASSWORD: inicio
      POSTGRES_DB: inicio
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  data:
  pgdata:

