version: '3.8'

services:
  web:
    image: node:21-alpine
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://postgres:postgres@db:5432/mydb
    command: sh -c "npm install && npm run dev"

