services:
  websocket:
    image: lakhoune/yjs-websocket
    ports:
      - "1234:1234"
    environment:
      HOST: 0.0.0.0
      PORT: 1234
  db:
    image: postgres:17
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: inicio
      POSTGRES_PASSWORD: inicio
      POSTGRES_DB: inicio-db
    volumes:
      - pgdata-inicio:/var/lib/postgresql/data
  s3:
    image: 'quay.io/minio/minio:latest'
    command: 'server /data --console-address ":9001"'
    environment:
      - MINIO_ROOT_USER=inicio
      - MINIO_ROOT_PASSWORD=inicio123
    volumes:
      - 'minio_data:/data'
    ports:
      - 9000:9000 # S3
      - 9001:9001 # UI

volumes:
  pgdata-inicio:
  minio_data:
