services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
    environment:
      NODE_ENV: production
      DATABASE_URL: postgres://postgres:postgres@db:5432/inicio-db
    depends_on:
      - db

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inicio-db
    volumes:
      - pgdata-inicio:/var/lib/postgresql/data

volumes:
  pgdata-inicio:

