name: Deploy WS
run-name: Deploy WS to ${{ github.ref_name == 'main' && 'Production' || 'Staging' }}

on:
  push:
    branches:
      - main
      - develop
    paths:
      - "inicio-ws/**"

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name }}

    steps:
      - name: Upload to NIployments register
        uses: NIAEFEUP/push-to-niployments@v2.2
        with:
          docker_dockerfile: Dockerfile
          docker_context: inicio-ws
          repository_name: inicio-ws
          NIPLOYMENTS_REGISTRY_URL: ${{ vars.NIPLOYMENTS_REGISTRY_URL }}
          NIPLOYMENTS_REGISTRY_USERNAME: ${{ vars.NIPLOYMENTS_REGISTRY_USERNAME }}
          NIPLOYMENTS_REGISTRY_PASSWORD: ${{ secrets.NIPLOYMENTS_REGISTRY_PASSWORD }}
